config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  resources :users
  resources :sessions
  resources :events
  resources :discussions
  delete '/joins' => 'joins#destroy'
  resources :joins
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :joins
  has_many :users_joined, through: :joins, source: :user
  has_many :discussions

  validate :date_must_be_post_current

  def date_must_be_post_current
    if date.present? && date < Date.today
      errors.add(:date, "must be later than today!!")
    end
  end

  validates :name, :location, :location_state, :date, presence: true


end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :events
  has_many :joins
  has_many :events_joined, through: :joins, source: :event
  has_many :discussions
  has_many :events_discussed, through: :discussions, source: :event
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name, :last_name, :email, :location, :location_state, presence: true
  validates :email, format: { with: EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 8 }, presence: true, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login, except: [:new,:create]

  private

  def require_login
    unless session[:user_id]
      puts "User isn't logged in..."
      flash[:alert] = "You must be logged in to access this page"
      redirect_to "/" # halts request cycle
    end
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  protect_from_forgery with: :exception
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

  def create
    discussion = Discussion.new( comment_params )
    puts discussion.comment
    if discussion.save
    else
      puts "errors"
      flash[:errors] = discussion.errors.full_messages
    end
    redirect_to "/events/#{discussion.event_id}"
  end

  private
  def comment_params
    params.require(:discussion).permit(:comment, :user_id, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @events_by_state = Event.where :location_state => current_user.location_state
    @user = current_user
    @event = Event.new
    @join = Join.all
  end

  def new
  end

  def create
    @event = Event.new( event_params )
    flash[:errors] = @event.errors.full_messages unless @event.save
    redirect_to events_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update( event_params )
      redirect_to events_path
    else
      redirect_to "/events/#{params[:id]}/edit"
    end
  end

  def show
    @event = Event.find(params[:id])
    @users_joined = @event.users_joined
    @discussion = Discussion.new
    @discussions = Discussion.where(event:@event.id)
  end

  def destroy
    event = Event.find(params[:id]).destroy
    redirect_to events_path
  end

  private
  def event_params
    params.require(:event).permit(:name, :location, :location_state, :date, :user_id)
  end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
  before_action :require_login

  def create
    join = Join.new( join_params )
    flash[:errors] = join.errors.full_messages unless join.save
    redirect_to events_path
  end

  def destroy
    join = Join.where( join_params )
    join_id = Join.find_by(user: current_user, event: (join_params[:event_id]))
    Join.find(join_id.id).destroy
    redirect_to events_path
  end

  private
  def join_params
    params.permit(:event_id, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # exclude index from require_login
  before_action :require_login, except: ['index', 'create']

  def new
  end

  def index
    @users = User.new
  end

  def create
    user = User.find_by_email(params[:email])
    # puts user.email
    if user && user.authenticate(params[:password])
      # puts "in create IF"
      session[:user_id] = user.id
      redirect_to events_path
    else
      flash[:errors] = ["Email/Password not found"]
      # puts "In create else"
      redirect_to "/"
    end
  end

  def destroy
    reset_session
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.new
  end

  def new
  end

  def create
    @user = User.new( user_params )
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      # puts session[:user_id]
      redirect_to events_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to "/"
    end
  end

  def show
  end

  def destroy
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update( user_edit_params )
      redirect_to events_path
    else
      flash[:alert] = @user.errors.full_messages
      redirect_to "/users/#{session[:user_id]}/edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :location, :location_state, :password, :password_confirmation)
  end
  def user_edit_params
    params.require(:user).permit(:first_name, :last_name, :email, :location, :location_state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/discussions/create.html.erb
<h1>Discussions#create</h1>
<p>Find me in app/views/discussions/create.html.erb</p>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Edit Event: <%= @event.name %></h1>
<%= form_for @event, :url => { :action => "update"}, method: :patch do |f| %>
  <%= f.hidden_field :user_id, value: session[:user_id] %>
  <p>
    Event Name: <%= f.text_field :name %><br />
  </p>
  <p>
    Location: <%= f.text_field :location %> State: <%= f.select :location_state, Event::STATES.keys, {include_blank: "-- Select --"} %>
  </p>
  <p>
    Event Date: <%= f.datetime_select :date %><br />
  </p>
  <p>
    <%= f.submit "Update Event" %>
  </p>
  <a href="/events#index">back</a>
<% end %>

app/views/events/index.html.erb
<h1>Events</h1>
<h3>Hello <%= @user.first_name %> from <%= @user.location_state %></h3>

<h4>Here are some of the events in your state:</h4>
<table>
  <thead>
    <th>Name</th>
    <th>Date</th>
    <th>Location</th>
    <th>State</th>
    <th>Host</th>
    <th>Action</th>
  </thead>
  <tbody>
    <% @events_by_state.each do |event_by_location|  %>
    <tr>
      <td><%= link_to "#{event_by_location.name}", event_path(event_by_location.id) %></td>
      <td><%= event_by_location.date.strftime("%b %d, %Y - %l:%M%p") %></td>
      <td><%= event_by_location.location %></td>
      <td><%= event_by_location.location_state %></td>
      <td><%= event_by_location.user.first_name %> <%= event_by_location.user.last_name %></td>
      <td>
        <% if event_by_location.user == current_user %>
          <a href="/events/<%= event_by_location.id %>/edit">Edit</a>
          <%= link_to 'Delete', event_by_location, method: :delete, data: {confirm: 'Are you certain'} %>
        <% elsif event_by_location.joins.where(user_id:session[:user_id], event_id:event_by_location.id) != [] %>
          Joined
          <%= link_to "Cancel", joins_path(user_id: session[:user_id], event_id: event_by_location.id), method: :delete %>
        <% else %>
          <%= link_to 'Join', joins_path(user_id: session[:user_id], event_id: event_by_location.id), method: :post %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<h4>Here are all events:</h4>
<table>
  <thead>
    <th>Name</th>
    <th>Date</th>
    <th>Location</th>
    <th>State</th>
    <th>Host</th>
    <th>Action</th>
  </thead>
  <tbody>
    <% @events.each do |event|  %>
    <tr>
      <td><%= link_to "#{event.name}", event_path(event.id) %></td>
      <td><%= event.date.strftime("%b %d, %Y - %l:%M%p") %></td>
      <td><%= event.location %></td>
      <td><%= event.location_state %></td>
      <td><%= event.user.first_name %> <%= event.user.last_name %></td>
      <td>
        <% if event.user == current_user %>
          <a href="/events/<%= event.id %>/edit">Edit</a>
          <%= link_to 'Delete', event, method: :delete, data: {confirm: 'Are you certain'} %>
        <% elsif event.joins.where(user_id:session[:user_id], event_id:event.id) != [] %>
          Joined
          <%= link_to "Cancel", joins_path(user_id: session[:user_id], event_id: event.id), method: :delete %>
        <% else %>
          <%= link_to 'Join', joins_path(user_id: session[:user_id], event_id: event.id), method: :post %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<h3>Post a new Event!</h3>

<% flash.each do |key, value| %>
  <%= content_tag :p, value %>
<% end %>

<%= form_for @event, :url => { :action => "create"} do |f| %>
  <%= f.hidden_field :user_id, value: session[:user_id] %>
  <p>
    Event Name: <%= f.text_field :name %><br />
  </p>
  <p>
    location: <%= f.text_field :location %><br />
  </p>
  <p>
    State: <%= f.select :location_state, Events::Application::STATES.keys, {include_blank: "-- Select --"} %><br />
  </p>
  <p>
    Date: <%= f.datetime_select :date %><br />
  </p>
  <%= f.submit "Add Event" %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>
<h3>Hello</h3>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p>
  Event Host: <%= @event.user.first_name %> <%= @event.user.last_name %>
</p>
<p>
  Event Date: <%= @event.date.strftime("%b %d, %Y - %l:%M%p") %>
</p>

<p>
  Event Location: <%= @event.location %>, <%= @event.location_state %>
</p>
<p>
  # of attendees (excluding Host): <%= @event.users_joined.count %>
</p>
<a href="/events#index">back</a>
<h4>Members of this event:</h4>
<table>
  <thead>
    <th>Name</th>
    <th>State</th>
  </thead>
  <tbody>
    <% @users_joined.each do |u| %>
    <tr>
      <td><%= u.first_name %> <%= u.last_name %></td>
      <td><%= u.location_state %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h4>Join the Discussion!</h4>
<%= form_for @discussion, :url => url_for(:controller => 'discussions', :action => "create") do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :event_id, value: @event.id %>
  <p>
    <%= f.label :comment %>
    <%= f.text_area :comment %><br />
  </p>
  <%= f.submit "Submit Comment" %>
<% end %>

<h4>Event Discussion</h4>
<div class="discussion">
  <% @discussions.each do |discussion| %>
    <p>
        <%= discussion.user.first_name %> <%= discussion.user.last_name %> says: <%= discussion.comment %>
    </p>
    _________________________________
  <% end %>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/joins/cancel.html.erb
<h1>Joins#cancel</h1>
<p>Find me in app/views/joins/cancel.html.erb</p>

app/views/joins/create.html.erb
<h1>Joins#create</h1>
<p>Find me in app/views/joins/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if session[:user_id] %>
      <p>
        Hello, <%= User.find(session[:user_id]).first_name %> <%= User.find(session[:user_id]).last_name %> |
        <a href="/users/<%= current_user.id %>/edit">Edit Profile</a> |
        <a href="/sessions/<%= session[:user_id] %>" data-method="delete">Logout</a>
      </p>
      __________________________
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1><%= current_user.first_name %> <%= current_user.last_name %></h1>
<%= flash[:alert] %>
<%= form_for @user, method: :patch do |f| %>
  <p>
    First Name: <%= f.text_field :first_name %>
  </p>
  <p>
    Last Name: <%= f.text_field :last_name %>
  </p>
  <p>
    Email: <%= f.text_field :email %>
  </p>
  <p>
    Location: <%= f.text_field :location %> State: <%= f.select :location_state, Event::STATES.keys, {include_blank: "-- Select --"} %>
  </p>
  <p>
    <%= f.submit "Update User" %>
  </p>
  <a href="/events#index">back</a>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Registration Form</h1>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>